name: run web automated tests

on:
  workflow_dispatch:
    inputs:
      test-tags-to-include:
        description: 'smoke or regression'
        required: false
        default: 'smoke'
        type: choice
        options:
          - 'smoke'
          - 'regression'
      environment:
        description: 'staging or dev'
        required: false
        default: 'staging'
        type: choice
        options:
          - 'dev'
          - 'staging'

jobs:
  web-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      selenium-chrome:
        image: selenium/standalone-chrome:110.0
        options: >-
          --shm-size "2g"
        ports:
          - 4444:4444

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        timeout-minutes: 30
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: execute-web-tests
        run: |
          mvn clean test -Dgroups="${{ inputs.test-tags-to-include }} & web"-Dselenide.remote=http://localhost:4444/wd/hub-Denvironment=${{ inputs.environment }} -Dselenide.browser=chrome
